<Myscreenmanager>:
    MenuScreen:
        name: "menu"
    VentaScreen:
        name: "vender"
    AgregarScreen:
        name: "agregar"
    Screenview:
        name: "inventario"
    Screenservice:
        name: "servicios"

<MenuScreen>:
    BoxLayout:
        orientation:'vertical'
        spacing: 20
        padding: 50

        Button:
            text: 'Servicios Disponibles'
            on_release:
                app.root.current = "servicios"

        Button:
            text: 'agregar productos'
            on_release:
                app.root.current = "agregar"

        Button: 
            text: 'vender Producto'
            on_release:
                app.root.current = "vender"
        Button:
            text: 'inventario'
            on_press: app.root.current = "inventario"
        
        Button:
            text: 'Salir'
            on_press: root.back()

<VentaScreen>:
    BoxLayout: 
        orientation: 'vertical'
        Ventasclass:
            id: venta 
            
            Button:
                text: "Realizar venrta"
                on_press: venta.realizar_venta()
        Button:
            text: ''
            size_hint: None, None
            size: '100dp', '100dp'
            background_normal: "Frontend/image/home.png"
            canvas.before:
                RoundedRectangle:
                    pos: self.pos                         
                    size: self.size
                    radius: [150]
            on_release:
                app.root.current = "menu"

<AgregarScreen>:
    BoxLayout:
        orientation: 'vertical'
        Add:
            id: agregar


        Button:
            text: ''
            size_hint: None, None
            size: '100dp', '100dp'
            background_normal: "Frontend/image/home.png"
            canvas.before:
                RoundedRectangle:
                    pos: self.pos                         
                    size: self.size
                    radius: [150]
            on_release:
                app.root.current = "menu"

<Screenview>:
    BoxLayout:
        orientation: 'vertical'
        spacing: 20
        padding: 50

        View:
            id: _inventario_

    
            
        Button:
            text: ''
            size_hint: None, None
            size: '100dp', '100dp'
            background_normal: "Frontend/image/home.png"
            canvas.before:
                RoundedRectangle:
                    pos: self.pos                         
                    size: self.size
                    radius: [150]
            on_release:
                app.root.current = "menu"

<Screenservice>:
    on_pre_enter: _serv_.servis_list()
    BoxLayout:
        orientation: 'vertical'
        spacing: '10dp'
        padding: '10dp'

        Servicios:
            id: _serv_

        Button:
            text: 'Aplicar'
            size_hint: None,None
            size: '100dp','50dp'
            background_normal: ''
            background_color: 0,128,0
            pos_hint: {"x":0.9,"y":0.0}
            on_press: _serv_.show_selected()

        Button:
            text: ''
            size_hint: None, None
            size: '100dp', '100dp'
            background_normal: "Frontend/image/home.png"
            canvas.before:
                RoundedRectangle:
                    pos: self.pos                         
                    size: self.size
                    radius: [150]
            on_release:
                app.root.current = "menu"



